name: Deploy Dockerized Hello World App to GKE

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Docker Image to GAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIAL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Build Docker image
        run: |
           gcloud auth configure-docker us-west1-docker.pkg.dev
           docker build -t us-west1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/hello-world/my-image:latest .
        
      - name: Push Docker image to GAR
        run: |
           docker push us-west1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/hello-world/my-image:latest

  terraform:
    name: Set up GKE Cluster with Terraform
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIAL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          google_credentials_file: ${{ secrets.GOOGLE_CREDENTIAL }}

  deploy:
    name: Deploy Application to GKE
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIAL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Apply Kubernetes deployment
        run: |
        gcloud container clusters get-credentials hello-world-cluster --zone us-west1-a
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" deployment.yaml
        kubectl apply -f deployment.yaml

  wait_for_loadbalancer:
    name: Wait for LoadBalancer IP
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Wait for LoadBalancer IP
        run: |
          while ! kubectl get svc hello-world-service | grep "EXTERNAL-IP" | grep -v "<pending>"; do
            echo "Waiting for LoadBalancer IP...";
            sleep 10;
          done
          echo "LoadBalancer IP is ready"